# Generated by Django 2.0.4 on 2018-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subscription',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
