# Generated by Django 2.0.4 on 2018-05-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_contact_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subscription',
            new_name='subscribe',
        ),
    ]
